function ViewLearningToolElement(a,l,g){function m(){CCL.CommonFunctions.safeAjaxPost({url:a.webMethods.checkCopyStatus.replace("{elementId}",a.elementId)}).done(function(b){b.status!=a.enums.copyStatus.inProgress&&(clearInterval(k),$("#"+a.controls.progressPanel).hide(),f().toggleCloseLink(!1),b.status==a.enums.copyStatus.completed?a.isCopy||f().showMessage(a.enums.feedbackType.information,a.terms.creatingNewVersionSucceededFeedback):b.status==a.enums.copyStatus.failed?a.isCopy?f().showMessage(a.enums.feedbackType.warning,
a.terms.creatingCopyFailedFeedback):f().showMessage(a.enums.feedbackType.warning,a.terms.creatingNewVersionFailedFeedback):b.status!=a.enums.copyStatus.none||a.isCopy?f().showMessage(a.enums.feedbackType.information,a.terms.copyingStatusChangedFeedback):f().showMessage(a.enums.feedbackType.information,a.terms.creatingNewVersionSucceededFeedback))}).error(function(){clearInterval(k)})}function n(b){var c=$("."+a.cssClasses.pageFunctionDependsFromElementActivation);c&&c.length&&(c.toggleHyperlink(b),
c.toggleClass(a.cssClasses.inactive,!b))}function r(){return $("#"+a.controls.pageFunctionsCogwheelMenu+" ul li").filter(function(){return"none"!==$(this).css("display")}).length}function h(){var b=$("#"+a.controls.extensionIframe);return b&&b[0]&&b[0].contentWindow?b[0].contentWindow:null}var e=this,k,p=$("#"+a.controls.printLink),q=$("#"+a.controls.pageFunctionsCogwheel);(new CCL.AutoIframeResizer({extensionIframeId:a.controls.extensionIframe,extensionContentId:a.controls.extensionContent,iosScrollFixClass:a.cssClasses.iosScrollFix,
resizeIframeWidth:a.resizeExtensionIframeWidth})).init();var t=new ItslearningWeb.Onboarding.ViewLearningToolElement.PostMessageDispatcher;if(h()){var u=$("#"+a.controls.extensionIframe);t.init(a.onboardingServiceUrl,u,a)}CommonFunctions.attachPostMessageEventListener($(window),a.refreshTreeMenuMessageName,function(){var b;(b=window.parent)&&window!=b&&CommonFunctions.makePostMessageCall(b,{messageName:a.refreshTreeMenuMessageName,elementId:a.elementId,folderId:a.folderId})});CommonFunctions.attachPostMessageEventListener($(window),
a.refreshElementFrameMessageName,function(){window.location.reload(!0)});$("#"+a.controls.copyLink).on("click",function(b){a.isShared?($("#"+a.controls.linkText).val($("#"+a.controls.embedUrlHidden).val()),$("#"+a.controls.embedCodeText).val($("#"+a.controls.embedCodeHidden).val()),window[a.controls.linkOrEmbedDialog].openDialog()):(b.preventDefault(),b.stopPropagation())});CommonFunctions.attachPostMessageEventListener($(window),CommonWindowMessages.MessageNames.openPersonProfileCard,function(a){document.showProfileCard(a.extendedData)});
CommonFunctions.attachPostMessageEventListener($(window),CommonWindowMessages.MessageNames.backToPreviousPage,function(){document.location.replace(a.backPageUrl)});CommonFunctions.attachPostMessageEventListener($(window),CommonWindowMessages.MessageNames.cloudFilePermissionError,function(){window.location.replace(a.cloudFilePermissionErrorUrl)});CommonFunctions.attachPostMessageEventListener($(window),CommonWindowMessages.MessageNames.askExtensionParentFrameWhetherTopFrameExists,function(){var a=
!1;try{a=window.self!==window.itslTop}catch(d){}var c=h();c&&a&&(a=new CCL.CommonWindowMessages.GenericMessage(CCL.CommonWindowMessages.MessageNames.replyToExtensionFrameWhenTopFrameExists),CCL.CommonFunctions.makePostMessageCall(c,a))});CommonFunctions.attachPostMessageEventListener($(window),CommonWindowMessages.MessageNames.askWhetherItslearningIsEmbedded,function(){var b=h();if(b&&a.isItslearningEmbedded){var c=new CCL.CommonWindowMessages.GenericMessage(CCL.CommonWindowMessages.MessageNames.replyIfItslearningIsEmbedded);
CCL.CommonFunctions.makePostMessageCall(b,c)}});CommonFunctions.attachPostMessageEventListener($(window),CommonWindowMessages.MessageNames.replaceTopFrame,function(a){if(a&&a.url){var b;(b=window.parent)&&window!==b?CommonFunctions.makePostMessageCallWithData(b,new CCL.CommonWindowMessages.GenericMessage(CommonWindowMessages.MessageNames.replaceTopFrame),{url:a.url}):window.location.replace(a.url)}});CommonFunctions.attachPostMessageEventListener($(window),CommonWindowMessages.MessageNames.scrollToTop,
function(){$(window).scrollTop(0)});g&&g();if(a.canEdit){a.copyStatus==a.enums.copyStatus.inProgress&&(k=setInterval(m,1E3));g=new ItslearningWeb.Controls.ElementTitleEditor($("#"+a.controls.titleLabel),a.elementTitleEditorClientSettings,a.elementId,a.folderId);if(l)$(g).on("change",l);$(g).on("change",function(a){var b=h();if(b){var d=new CCL.CommonWindowMessages.GenericMessage(CCL.CommonWindowMessages.MessageNames.extensionTitleUpdated);CCL.CommonFunctions.makePostMessageCallWithData(b,d,{newTitle:a})}})}(function(){CCL.CommonFunctions.attachPostMessageEventListener($(window),
CommonWindowMessages.MessageNames.elementAddedToYourCollection,function(){var b=window.location.href.split("#")[0];window.location.href=b.setQueryStringParameter(a.addedParam,(!0).toString())})})();(function(){CommonFunctions.attachPostMessageEventListener($(window),CommonWindowMessages.MessageNames.changePrintFeatureVisibility,function(a){a.visible?p.show():p.hide();0<r()?q.show():q.hide()})})();CCL.IframeContentHeightReporter.attachExtensionContentOpenedListenerForIframe(a.controls.extensionIframe,
a.resizeExtensionIframeWidth);n(a.isActive);e.closeManageRubricDialog=function(){var b=$("#"+a.rubricDialogClientInstanceName).find("iframe").get(0).contentWindow;CCL.CommonFunctions.makePostMessageCall(b,new CCL.CommonWindowMessages.GenericMessage(CCL.CommonWindowMessages.MessageNames.submitIframe))};e.showCopyConfirmation=function(b){$.alerts.okButton=b;$.alerts.cancelButton=a.terms.cancel;jConfirm(a.terms.startCopyingConfirmation,a.terms.pleaseConfirm,function(b){b&&CCL.CommonFunctions.safeAjaxPost({url:a.webMethods.startCopying.replace("{elementId}",
a.elementId)}).done(function(b){b.success&&(a.isCopy=!1,e.showProgressMessage(a.terms.creatingNewVersionProgressFeedback),k=setInterval(m,1E3))})})};e.showProgressMessage=function(b){$("#"+a.controls.progressPanel).show();$("#"+a.controls.createNewVersionLinkContainer).hide();$("#"+a.controls.editOriginalLinkContainer).hide();$("#"+a.controls.progressLabel).text(b);f().hide(!1)};e.flushCopyStatus=function(){CCL.CommonFunctions.safeAjaxPost({url:a.webMethods.flushCopyStatus.replace("{elementId}",a.elementId)})};
e.printContentFrame=function(){var b=h();if(b){var c=$("."+a.cssClasses.title).text(),d=$("."+a.cssClasses.container)[0].outerHTML;CommonFunctions.makePostMessageCall(b,{messageName:CommonWindowMessages.MessageNames.extensionPrintContentFrame,headerText:c,headerHtml:d})}return!1};e.notifyAboutChanges=function(){$.alerts.okButton=a.terms.ok;$.alerts.cancelButton=a.terms.cancel;jConfirm(a.terms.notifyAboutChangesConfirmation,a.terms.pleaseConfirm,function(b){b&&CCL.CommonFunctions.safeAjaxPost({url:a.webMethods.notifyAboutChanges,
data:{elementId:a.elementId}}).fail(CCL.CommonFunctions.alertAjaxError)});return!1};e.sendElementReminders=function(){$.alerts.okButton=a.terms.sendRemindersYes;$.alerts.cancelButton=a.terms.cancel;jConfirm(a.terms.sendRemindersDetails,a.terms.sendReminders,function(b){b&&CCL.CommonFunctions.safeAjaxPost({url:a.webMethods.sendReminders,data:{elementId:a.elementId}}).fail(CCL.CommonFunctions.alertAjaxError)});return!1};var f=function(){return window[a.copyStatusFeedbackInstanceName]};e.copyToClipboardOk=
function(b){var c=null,d=null;"CopyLink"==b?(c=$("#"+a.controls.linkText),d=$("#"+a.controls.copyLinkToClipboardOkIcon)):(c=$("#"+a.controls.embedCodeText),d=$("#"+a.controls.copyEmbedCodeToClipboardOkIcon));b=d.css("width");d.parent().css("width",b);(function(a){var b=document.createElement("input");b.style.position="fixed";b.style.opacity=0;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)})(c.val());d.prev().hide();d.fadeIn(500);setTimeout(function(){d.hide().prev().fadeIn(400)},
1E3)};e.changePageFunctionsState=function(a){n(a)}};
